apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: dmc-management
  labels:
    app: argo-cd
    type: tool
    dmc: dmc-management
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: dmc-management
  project: dmc-management
  source:
    path: charts/argo-cd
    repoURL: https://github.com/arthurk/argocd-example-install.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

