apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: dmc-management
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: dmc-management
#    server: https://kubernetes.default.svc
#    namespace: default
  project: default
  source:
    path: apps/
    repoURL: https://github.com/someshg/argotest
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
